### PR TITLE
fix: redundant calls fromJson in SchemaValidationError

### LINKED ISSUE #47: Upon a validation error, luthor still calls `fromJson` which may throw an error
Consider a non-nullable field is validated. If that field doesn't exist, the validation catches it but still tries to call `fromJson` which may throw a type error if `fromJson` is expecting a non-null value, which is intended. Single fix is to remove `data` from `SchemaValidationError`.

https://github.com/exaby73/luthor/blob/da7ea813d2badbcb7f0ae7b66e25353545b07032/packages/luthor/lib/src/validator.dart#L130-L142

### PR DESCRIPTION
**Pull request by kasefuchs**
Fixes #47

### CODE REVIEW

**Comment by kasefuchs** [comment]
222967480-8ced27ea-7898-4c95-9aab-3304019448eb

**Comment by exaby73** [comment]
Hi sorry for the late response :). Could you add tests for this? Also, by glance I see that the success case doesn't have a nullable data field, but could you confirm that?

**Comment by kasefuchs** [comment]
Hi. Yes, I will try to add tests. Also, according to my original plan, if validation is successful, the data field won't be able to have null values.

**Comment by kasefuchs** [comment]
Theres already a success case test here, so I dont think it needs to be written again.

https://github.com/exaby73/luthor/blob/1c1924a30d977c7cee9a72dc517a71c1d88e1949/packages/luthor/test/validations/schema_validation_test.dart#L154-L172

**Comment by exaby73** [comment]
Could you also add a test for when fromJson is null? It should not throw an error

**Comment by kasefuchs** [comment]
I think other already existing tests covers this case

**Review by exaby73 — APPROVED** [review]

**Comment by exaby73** [comment]
I’ll publish this change soon. I do want to also add Melos into this repository. So I might first add that then release

**Comment by exaby73** [comment]
@kasefuchs Thanks for the PR again. 0.2.1 is out with your fix :)

**Pull request merged**
